FROM opensuse/leap:15.4
LABEL maintainer "Andrei Poenaru <docker@simd.stream>"

RUN zypper install -y\
    autoconf \
    automake \
    byacc \
    bzip2 \
    libbz2-devel \
    cmake \
    curl \
    dirmngr \
    gcc \
    gcc-c++ \
    git \
    glib2-devel \
    gzip \
    kernel-devel \
    libcurl-devel \
    libevent-devel \
    libffi-devel \
    libjpeg8-devel \
    libopenssl-devel \
    libxml2-devel \
    libxslt-devel \
    make \
    ncurses-devel \
    openssl \
    postgresql-devel \
    readline-devel \
    sqlite3-devel \
    stow \
    tar \
    wget \
    which \
    xz \
    zlib-devel \
    && zypper clean --all
