---
kind: pipeline
type: docker
name: build-aarch64

platform:
  arch: arm64
  os: linux

steps:
  - name: build-latest
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15-aarch64
        - latest-aarch64
      dockerfile: 15/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
  - name: build-15.0
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.0-aarch64
      dockerfile: 15.0/Dockerfile.aarch64
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
  - name: build-15.1
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.1-aarch64
      dockerfile: 15.1/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-15.2
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.2-aarch64
      dockerfile: 15.2/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-15.3
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.3-aarch64
      dockerfile: 15.3/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-15.4
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.4-aarch64
      dockerfile: 15.4/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-15.5
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.5-aarch64
      dockerfile: 15.5/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-15.6
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.6-aarch64
      dockerfile: 15.6/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: build-latest
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15-amd64
        - latest-amd64
      dockerfile: 15/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
  - name: build-15.0
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.0-amd64
      dockerfile: 15.0/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
  - name: build-15.1
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.1-amd64
      dockerfile: 15.1/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-15.2
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.2-amd64
      dockerfile: 15.2/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-15.3
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.3-amd64
      dockerfile: 15.3/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-15.4
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.4-amd64
      dockerfile: 15.4/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-15.5
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.5-amd64
      dockerfile: 15.5/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-15.6
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-suse
      tags:
        - 15.6-amd64
      dockerfile: 15.6/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: multiarch-manifest

steps:
  - name: manifest-latest
    image: plugins/manifest
    settings:
      spec: 15/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-15.0
    image: plugins/manifest
    settings:
      spec: 15.0/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-15.1
    image: plugins/manifest
    settings:
      spec: 15.1/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
    when:
      status: [success, failure]
  - name: manifest-15.2
    image: plugins/manifest
    settings:
      spec: 15.2/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
    when:
      status: [success, failure]
  - name: manifest-15.3
    image: plugins/manifest
    settings:
      spec: 15.3/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
    when:
      status: [success, failure]
  - name: manifest-15.4
    image: plugins/manifest
    settings:
      spec: 15.4/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
    when:
      status: [success, failure]
  - name: manifest-15.5
    image: plugins/manifest
    settings:
      spec: 15.5/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
    when:
      status: [success, failure]
  - name: manifest-15.6
    image: plugins/manifest
    settings:
      spec: 15.6/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
    when:
      status: [success, failure]
  - name: healthcheck
    image: ubuntu
    environment:
      HEALTHCHECKS_URL:
        from_secret: healthchecks_url
    commands:
      - apt-get update
      - apt-get -y install curl
      - |
        if [ ${DRONE_BUILD_STATUS} = success ]; then
          curl --retry 3 $${HEALTHCHECKS_URL}
        else
          curl --retry 3 $${HEALTHCHECKS_URL}/fail
        fi
    when:
      status: [success, failure]

depends_on: [build-aarch64, build-amd64]
trigger:
  status: [success, failure]

---
kind: signature
hmac: a81354d004790728c37e6b6c8fbc58396da1bbcbf8d818fe0e00caf40fe1cbf1

...
